name: Vercel Production Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Create Vercel Project Link
        working-directory: my-app
        run: |
          mkdir -p .vercel
          printf '{"orgId":"%s","projectId":"%s","projectName":"m-shop"}' \
          "$VERCEL_ORG_ID" "$VERCEL_PROJECT_ID" > .vercel/project.json

      - name: Deploy to Vercel
        working-directory: my-app
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
